routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

//protect all routes from guests!
Route::group(['middleware' => 'auth'], function(){


	
Route::get('/home', 'HomeController@index')->name('home');

Route::post('update_profile', 'HomeController@update');

Route::resource('/post', 'PostController');

Route::resource('/comment', 'CommentController');

Route::resource('/community', 'CommunityController');

Route::post('/ajaxReq', 'AjaxRequestController@uniqueCredentials');

Route::get('/schools', 'AjaxRequestController@getSchools');

Route::get('/countries', 'AjaxRequestController@getCountries');

//get replies
Route::get('/comments/replies/{id}', 'AjaxRequestController@getReplies');

//get watchers suggessions
Route::get('/getWatchersSuggestion', 'HomeController@getWatchersSuggestion');

//watch route
Route::post('/watch', 'HomeController@watching');

//get user -vue
Route::get('/getUser/{id}', 'AjaxRequestController@getUser');

Route::get('/getUserPosts/{id}', 'AjaxRequestController@getUserPosts');

//blog index
Route::get('/blog', 'BlogController@index');

//getblogposts
Route::get('get_blog_posts', 'BlogController@getPosts');

//get single  post
Route::get('getSinglePost/{id}', 'AjaxRequestController@getSinglePost');

});


Route::group(['middleware'=>'auth', 'middleware'=>'control'], function(){

// admin dashboard
Route::get('control/admin', 'AdminController@index');

//show all posts
Route::get('control/posts', 'AdminController@allPosts')->name('all_blog_posts');

//addNew post get
Route::get('control/add_new_post', 'AdminController@addNewPost');

//view_edit single post
Route::get('control/post/{id}', 'AdminController@viewUpdatePost')->name('viewUpdatePost');

Route::get('/test', 'HomeController@getWatchersSuggestion');
});

//user page route
Route::get('/{username}', 'HomeController@UserPage')->middleware('auth');

resources/views/test_views/community.blade.php
@extends('layouts.app')



@section('content')

<div class="container">
	<div class="row">
		<form action="{{route('comunity.store')}}" method="post" enctype="multipart/form-data">
			@csrf
			<input type="text" name="name" class="form-control">
			<textarea name="description" class="form-control"></textarea>
			<input type="file" name="image">
			<button name="submit" type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>
	<br><br>
	<hr>
	<div class="row">
		<ul class="list-group">
		@foreach($communities as $community)
		<li class="list-group-item">{{$community->name}}</li>
		<br>
		<form action="{{ route('comunity.update', $community->id) }}" method="post">
			@csrf
			@method('put')
			<input type="hidden" name="type" value="join">
			<button class="btn btn-sm btn-info" type="submit">Join</button>
		</form>
		<br>
		<form action="{{ route('comunity.destroy', $community->id) }}" method="post">
			@csrf
			@method('delete')
			<button class="btn btn-sm btn-danger" type="submit">delete</button>
		</form>
	    </br>
		@endforeach
		</ul>
	</div>
</div>



@endsection

resources/views/test_views/post.blade.php
@extends('layouts.app')


@section('content')

@if($posts)

  <ul>
  	@foreach($posts as $post)
  	<li class="list-item">
  		@if($post->image != null)
  		<?php  
  		   $images = explode(',', $post->image);
  		?>
  		   @foreach($images as $image)
  		    <img src="storage/image/{{$image}}" width="200" height="100" alt="image">
  		   @endforeach
  		@endif
  		@if($post->video != null)
  		   @foreach($post->video as $video)
  		    <video width="200px" height="100px" controls>
  		    	<source src="storage/video/{{$video}}" type="video/*">
  		    </video> 
  		   @endforeach
  		@endif
  		@if($post->audio != null)
  		   @foreach($post->audio as $audio)
  		    <img src="storage/audio/{{$audio}}" width="200" height="100">
  		   @endforeach
  		@endif
  		<div class="panel-title">
  			{{$post->title}}
  		</div>
  		<div class="panel-body">
  			{{$post->body}}
  		</div>
  		<form action="{{route('post.update', $post->id)}}" method="post">
  			@csrf
  			@method('put')
  			<input type="hidden" name="type" value="smile">
  			<button class="btn btn-sm btn-info">Smile</button>
  		</form>
  		<hr>
  		@foreach($post->comments as $comment)
  		   <span class="alert">{{$comment->comment}}</span>
  		@endforeach
  		<hr>
  		<form action="{{route('comment.store')}}" method="post">
  			@csrf
  			<textarea class="form-control" name="comment" cols="30" rows="1"></textarea>
  			<input type="hidden" name="post_id" value="{{$post->id}}">
  			<input type="hidden" name="type" value="comment">
  			<br>
  			<button class="btn btn-sm btn-primary">Comment</button>
  		</form>
  		<br><br>
  	</li>
  	@endforeach
  </ul>

@endif

@endsection

resources/views/test_views/testView.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

<title>{{ config('app.name', 'Laravel') }}</title>

	<!-- Required meta tags always come first -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="x-ua-compatible" content="ie=edge">

	<!-- Main Font -->
    <script src="{{ asset('olympus/js/webfontloader.min.js')}}"></script>
    <script>
        WebFont.load({
            google: {
                families: ['Roboto:300,400,500,700:latin']
            }
        });
    </script>

    <meta name="csrf-token" content="{{ csrf_token() }}">

     <script src="{{ asset('js/app.js') }}" defer></script>
     
     <script>
     	window.laravel = {
               'userId': '{{ctId()}}',
               'username': '{{ctName()}}',
               'user_photo': '{{ctUser()->profile_photo}}',
               'fullname': '{{ctUser()->fullname}}',
               'csrf_token': '{{ csrf_token() }}'
     	}
     </script>
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" 
		  type="text/css" 
		  href="{{ asset('olympus/Bootstrap/dist/css/bootstrap-reboot.css') }}">

	<link rel="stylesheet" 
	      type="text/css" 
	      href="{{ asset('olympus/Bootstrap/dist/css/bootstrap.css')}}">

	<link rel="stylesheet" 
	      type="text/css" 
	      href="{{ asset('olympus/Bootstrap/dist/css/bootstrap-grid.css')}}">

	<!-- Main Styles CSS -->
	<link rel="stylesheet" 
	      type="text/css" 
	      href="{{ asset('olympus/css/main.min.css')}}">

	<link rel="stylesheet" 
	      type="text/css" 
	      href="{{ asset('olympus/css/fonts.min.css')}}">

</head>
<body class="body-bg-white">



<!-- Stunning header -->

<div class="stunning-header bg-primary-opacity">

	
	<!-- Header Standard Landing  -->
	
	<div class="header--standard header--standard-landing" id="header--standard">
		<div class="container">
			<div class="header--standard-wrap">
	
				<a href="#" class="logo">
					<div class="img-wrap">
						<img src="img/logo.png" alt="Olympus">
						<img src="img/logo-colored-small.png" alt="Olympus" class="logo-colored">
					</div>
					<div class="title-block">
						<h6 class="logo-title">olympus</h6>
						<div class="sub-title">SOCIAL NETWORK</div>
					</div>
				</a>
	
				<a href="#" class="open-responsive-menu js-open-responsive-menu">
					<svg class="olymp-menu-icon"><use xlink:href="svg-icons/sprites/icons.svg#olymp-menu-icon"></use></svg>
				</a>
	
				<div class="nav nav-pills nav1 header-menu">
					<div class="mCustomScrollbar">
						<ul>
							<li class="nav-item">
								<a href="#" class="nav-link">Home</a>
							</li>
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" data-hover="dropdown" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false" tabindex='1'>Profile</a>
								<div class="dropdown-menu">
									<a class="dropdown-item" href="#">Profile Page</a>
									<a class="dropdown-item" href="#">Newsfeed</a>
									<a class="dropdown-item" href="#">Post Versions</a>
								</div>
							</li>
							<li class="nav-item dropdown dropdown-has-megamenu">
								<a href="#" class="nav-link dropdown-toggle" data-hover="dropdown" data-toggle="dropdown" role="button" aria-haspopup="false" aria-expanded="false" tabindex='1'>Forums</a>
								<div class="dropdown-menu megamenu">
									<div class="row">
										<div class="col col-sm-3">
											<h6 class="column-tittle">Communities</h6>
											<a class="dropdown-item" href="#">Profile Page</a>
										</div>
									</div>
								</div>
							</li>
							<li class="nav-item">
								<a href="#" class="nav-link">Terms & Conditions</a>
							</li>
							<li class="nav-item">
								<a href="#" class="nav-link">Events</a>
							</li>
							<li class="nav-item">
								<a href="#" class="nav-link">Privacy Policy</a>
							</li>
							<li class="close-responsive-menu js-close-responsive-menu">
								<svg class="olymp-close-icon"><use xlink:href="svg-icons/sprites/icons.svg#olymp-close-icon"></use></svg>
							</li>
							<li class="nav-item js-expanded-menu">
								<a href="#" class="nav-link">
									<svg class="olymp-menu-icon"><use xlink:href="svg-icons/sprites/icons.svg#olymp-menu-icon"></use></svg>
									<svg class="olymp-close-icon"><use xlink:href="svg-icons/sprites/icons.svg#olymp-close-icon"></use></svg>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<!-- ... end Header Standard Landing  -->
	<div class="header-spacer--standard"></div>

	<div class="stunning-header-content">
		<h1 class="stunning-header-title">Blog List</h1>
		<ul class="breadcrumbs">
			<li class="breadcrumbs-item">
				<a href="#">Home</a>
				<span class="icon breadcrumbs-custom">/</span>
			</li>
			<li class="breadcrumbs-item active">
				<span>Blog List</span>
			</li>
		</ul>
	</div>

	<div class="content-bg-wrap stunning-header-bg1"></div>
</div>

<!-- End Stunning header -->

<!-- push posts an feature posts here -->

<!-- Footer Full Width -->

<div class="footer footer-full-width" id="footer">
	<div class="container">
		<div class="row">
			<div class="col col-lg-4 col-md-4 col-sm-6 col-6">

				

				<!-- Widget About -->
				
				<div class="widget w-about">
				
					<a href="02-ProfilePage.html" class="logo">
						<div class="img-wrap">
							<img src="img/logo-colored.png" alt="Olympus">
						</div>
						<div class="title-block">
							<h6 class="logo-title">olympus</h6>
							<div class="sub-title">SOCIAL NETWORK</div>
						</div>
					</a>
					<p>Lorem ipsum dolor sit amet, consect adipisicing elit, sed do eiusmod por incidid ut labore et lorem.</p>
					<ul class="socials">
						<li>
							<a href="#">
								<i class="fab fa-facebook-square" aria-hidden="true"></i>
							</a>
						</li>
						<li>
							<a href="#">
								<i class="fab fa-twitter" aria-hidden="true"></i>
							</a>
						</li>
						<li>
							<a href="#">
								<i class="fab fa-youtube" aria-hidden="true"></i>
							</a>
						</li>
						<li>
							<a href="#">
								<i class="fab fa-google-plus-g" aria-hidden="true"></i>
							</a>
						</li>
						<li>
							<a href="#">
								<i class="fab fa-instagram" aria-hidden="true"></i>
							</a>
						</li>
					</ul>
				</div>
				
				<!-- ... end Widget About -->

			</div>

			<div class="col col-lg-2 col-md-4 col-sm-6 col-6">

				
				<!-- Widget List -->
				
				<div class="widget w-list">
					<h6 class="title">Main Links</h6>
					<ul>
						<li>
							<a href="/login">Landing</a>
						</li>
						<li>
							<a href="/home">Home</a>
						</li>
						<li>
							<a href="/about">About</a>
						</li>
						<!-- <li>
							<a href="#">Events</a>
						</li> -->
					</ul>
				</div>
				
				<!-- ... end Widget List -->

			</div>
			<div class="col col-lg-2 col-md-4 col-sm-6 col-6">

				
				<div class="widget w-list">
					<h6 class="title">Your dashboard</h6>
					<ul>
						<li>
							<a href="/home">Home</a>
						</li>
						<li>
							<a href="#">About Page</a>
						</li>
						<li>
							<a href="#">Watchers</a>
						</li>
					</ul>
				</div>

			</div>
			<div class="col col-lg-2 col-md-4 col-sm-6 col-6">

				
				<div class="widget w-list">
					<h6 class="title">Features</h6>
					<ul>
						<li>
							<a href="#">CT Blog</a>
						</li>
						<li>
							<a href="#">CT Tv</a>
						</li>
						<li>
							<a href="#">CT Community</a>
						</li>
						<li>
							<a href="#">CT Billboard</a>
						</li>
					</ul>
				</div>

			</div>
			<div class="col col-lg-2 col-md-4 col-sm-6 col-6">

				
				<div class="widget w-list">
					<h6 class="title">Campustalkative</h6>
					<ul>
						<li>
							<a href="#">Privacy</a>
						</li>
						<li>
							<a href="#">Terms & Conditions</a>
						</li>
						<li>
							<a href="#">About Us</a>
						</li>
					</ul>
				</div>

			</div>

			<div class="col col-lg-12 col-md-12 col-sm-12 col-12">

				
				<!-- SUB Footer -->
				
				<div class="sub-footer-copyright">
					<span>
						Copyright <a href="index-2.html">Olympus Buddypress + WP</a> All Rights Reserved 2017
					</span>
				</div>
				
				<!-- ... end SUB Footer -->

			</div>
		</div>
	</div>
</div>

<!-- ... end Footer Full Width -->




<a class="back-to-top" href="#">
	<img src="svg-icons/back-to-top.svg" alt="arrow" class="back-icon">
</a>



<!-- JS Scripts -->
<script src="{{ asset('olympus/jquery-3.2.1.js')}}"></script>
<script src="{{ asset('olympus/jquery.appear.js')}}"></script>
<script src="{{ asset('olympus/jquery.mousewheel.js')}}"></script>
<script src="{{ asset('olympus/perfect-scrollbar.js')}}"></script>
<script src="{{ asset('olympus/jquery.matchHeight.js')}}"></script>
<script src="{{ asset('olympus/svgxuse.js')}}"></script>
<script src="{{ asset('olympus/imagesloaded.pkgd.js')}}"></script>
<script src="{{ asset('olympus/Headroom.js')}}"></script>
<script src="{{ asset('olympus/velocity.js')}}"></script>
<script src="{{ asset('olympus/ScrollMagic.js')}}"></script>
<script src="{{ asset('olympus/jquery.waypoints.js')}}"></script>
<script src="{{ asset('olympus/jquery.countTo.js')}}"></script>
<script src="{{ asset('olympus/popper.min.js')}}"></script>
<script src="{{ asset('olympus/material.min.js')}}"></script>
<script src="{{ asset('olympus/bootstrap-select.js')}}"></script>
<script src="{{ asset('olympus/smooth-scroll.js')}}"></script>
<script src="{{ asset('olympus/selectize.js')}}"></script>
<script src="{{ asset('olympus/swiper.jquery.js')}}"></script>
<script src="{{ asset('olympus/moment.js')}}"></script>
<script src="{{ asset('olympus/daterangepicker.js')}}"></script>
<script src="{{ asset('olympus/simplecalendar.js')}}"></script>
<script src="{{ asset('olympus/fullcalendar.js')}}"></script>
<script src="{{ asset('olympus/isotope.pkgd.js')}}"></script>
<script src="{{ asset('olympus/ajax-pagination.js')}}"></script>
<script src="{{ asset('olympus/Chart.js')}}"></script>
<script src="{{ asset('olympus/chartjs-plugin-deferred.js')}}"></script>
<script src="{{ asset('olympus/circle-progress.js')}}"></script>
<script src="{{ asset('olympus/loader.js')}}"></script>
<script src="{{ asset('olympus/run-chart.js')}}"></script>
<script src="{{ asset('olympus/jquery.magnific-popup.js')}}"></script>
<script src="{{ asset('olympus/jquery.gifplayer.js')}}"></script>
<script src="{{ asset('olympus/mediaelement-and-player.js')}}"></script>
<script src="{{ asset('olympus/mediaelement-playlist-plugin.min.js')}}"></script>

<script src="{{ asset('olympus/base-init.js')}}"></script>
<script defer src="fonts/fontawesome-all.js')}}"></script>

<script defer src="{{ asset('olympus/fonts/fontawesome-all.js')}}"></script>

<script src="{{ asset('olympus/Bootstrap/dist/js/bootstrap.bundle.js')}}"></script>

</body>

</html>

resources/views/test_views/upload.blade.php
<form action="{{ route('post') }}" method="post" 
     enctype="multipart/form-data">
    <input type="text" name="title">
    <textarea name="body"></textarea>	
    <input type="file" name="image" multiple="">
    <button>Submit</button>
</form>

resources/views/test_views/user.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	<div class="row">
		<form action="{{route('updateUser')}}" method="post" 
		enctype="multipart/form-data">
			@csrf
			<input class="form-control" type="text" name="skills">
		    <input type="file" name="photos[]" multiple>
		    <textarea class="form-control" cols="30" rows="1" name="about"></textarea>
		    <select name="school_id" class="form-control">
		    	<option>--Choose School--</option>
		    	@foreach($schools as $school)
		    	<option class="form-control" value="{{$school->id}}">{{$school->school}}</option>
		    	@endforeach
		    </select>
		    <button class="btn btn-primary" type="submit">Update!</button>
		</form>
	</div>
</div>







@endsection

resources/views/test_views/watch.blade.php
@extends('layouts.app')


@section('content')
<div class="container">
	<div class="row">
   <form class="form" method="post" action="{{route('console')}}">
   	@csrf
   	   <input type="hidden" name="watched" value="ttttt">
   	   <button type="submit" class="btn btn-success">Watch</button>
   </form>
   <hr>
		
	</div>
</div>






@endsection